language: node_js

node_js:
   - lts/*

notifications:
    email: true

sudo: true

before_install:
    - yarn global add codecov

after_success:
    - codecov

services:
    - redis-server

notifications:
  email:
    - travis@bangingheads.net
